[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting = "Doe7Bt34WWnGjqNjTpfYksejhSKLPs7jEtWNwZLjm7KP"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --features no-entrypoint --test litesvm"

[hooks]
